services:
  portfolio:
    image: colechiodo/portfolio:latest
    ports:
      - "9050:9050"
    environment:
      - DB_PATH=/app/db/db.sqlite
    volumes:
      - portfolio-data:/app/db
    restart: unless-stopped

volumes:
  portfolio-data:
